# Generated by Django 5.0.6 on 2024-06-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_tic_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Телефон"),
        ),
    ]
