# Generated by Django 5.0.6 on 2024-06-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_pricecategory_event_max_visitors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventschedule",
            name="data",
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата мероприятия"
            ),
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="end_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время конца"
            ),
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="start_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время начало"
            ),
        ),
    ]
