# Generated by Django 5.0.6 on 2024-06-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_eventprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/organizations"
            ),
        ),
    ]
