# Generated by Django 5.0.6 on 2024-06-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_eventschedule_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventschedule",
            name="end_at",
            field=models.DateTimeField(default="2000-01-01", verbose_name="Дата и время конца"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventschedule",
            name="start_at",
            field=models.DateTimeField(default="2000-01-01", verbose_name="Дата и время начало"),
            preserve_default=False,
        ),
    ]
