# Generated by Django 5.0.6 on 2024-06-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_eventprice_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.TextField(default="", verbose_name="Адрес"),
            preserve_default=False,
        ),
    ]
