# Generated by Django 5.0.6 on 2024-06-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_eventprice_left_visitors"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="latitude",
            field=models.FloatField(default=1, verbose_name="Широта"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="longitude",
            field=models.FloatField(default=1, verbose_name="Долгота"),
            preserve_default=False,
        ),
    ]
