# Generated by Django 5.0.6 on 2024-06-12 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_organization_latitude_organization_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventprice",
            name="event",
        ),
        migrations.CreateModel(
            name="EventSchedulePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("CHILD", "Child"),
                            ("STUDENT", "Student"),
                            ("RETIREE", "Retiree"),
                        ],
                        max_length=255,
                        verbose_name="Категория покупателя",
                    ),
                ),
                (
                    "max_visitors",
                    models.PositiveIntegerField(
                        verbose_name="Максимальное количество посетителей категории"
                    ),
                ),
                (
                    "bitrix_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID в Bitrix"
                    ),
                ),
                (
                    "event_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="events.eventschedule",
                        verbose_name="Время мероприятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант билета",
                "verbose_name_plural": "Варианты билета",
            },
        ),
    ]
