# Generated by Django 5.0.6 on 2024-06-12 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_alter_eventschedule_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventschedule",
            name="group_id",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="Группа"),
        ),
    ]
