# Generated by Django 5.0.6 on 2024-06-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_eventschedule_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="age_limit",
            field=models.CharField(
                default="6+", max_length=1024, verbose_name="Возрастной ценз"
            ),
            preserve_default=False,
        ),
    ]
