# Generated by Django 5.0.6 on 2024-06-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_age_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventschedule",
            name="group_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Группа"),
        ),
    ]
