# Generated by Django 5.0.6 on 2024-06-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_event_abbreviation_organization_abbreviation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "events",
                    models.ManyToManyField(
                        related_name="sets",
                        to="events.event",
                        verbose_name="Мероприятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор мероприятий",
                "verbose_name_plural": "Наборы мероприятий",
            },
        ),
    ]
