# Generated by Django 5.0.6 on 2024-06-14 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_alter_eventscheduleprice_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventset",
            name="set_id",
            field=models.UUIDField(
                default=uuid.UUID("d93ae397-77e6-497e-8170-660bb8c69277"),
                verbose_name="ID единого билета",
            ),
        ),
    ]
