# Generated by Django 5.0.6 on 2024-06-14 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_alter_eventset_set_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventset",
            name="set_id",
            field=models.UUIDField(
                default=uuid.UUID("b01eeb0a-a492-4f1d-8243-4a2484b990f8"),
                editable=False,
                verbose_name="ID единого билета",
            ),
        ),
    ]
