# Generated by Django 5.0.6 on 2024-06-14 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_alter_eventset_set_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventset",
            name="set_id",
            field=models.UUIDField(
                default=uuid.UUID("3d6201ea-0b7a-49cd-affc-8c58279ddf54"),
                editable=False,
                verbose_name="ID единого билета",
            ),
        ),
    ]
