# Generated by Django 5.0.6 on 2024-06-14 13:34
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_alter_event_options_alter_eventimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventset",
            name="set_id",
            field=models.UUIDField(
                default=uuid.UUID("d93ae397-77e6-497e-8170-660bb8c69277"),
                editable=False,
                verbose_name="ID единого билета",
            ),
        ),
    ]
