# Generated by Django 5.0.6 on 2024-06-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_alter_eventset_set_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventset",
            name="bitrix_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID в Bitrix"
            ),
        ),
    ]
