# Generated by Django 5.0.6 on 2024-06-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0031_alter_eventscheduleprice_bitrix_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventscheduleprice",
            name="bitrix_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID в Bitrix"
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="bitrix_id",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="ID в Bitrix"
            ),
        ),
    ]
