# Generated by Django 5.0.6 on 2024-06-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0032_alter_eventscheduleprice_bitrix_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventset",
            name="bitrix_id",
        ),
    ]
