# Generated by Django 5.0.6 on 2024-06-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
                (
                    "file",
                    models.ImageField(blank=True, null=True, upload_to="media/organizations"),
                ),
            ],
            options={
                "verbose_name": "Кафе",
                "verbose_name_plural": "Кафе",
            },
        ),
    ]
