# Generated by Django 5.0.6 on 2024-06-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="media/cafes"),
        ),
    ]
