# Generated by Django 5.0.6 on 2024-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_purchase_options_remove_purchaseevent_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("Стандартный", "Standard"),
                    ("Детский", "Child"),
                    ("Студенческий", "Student"),
                    ("Пенсионер", "Retiree"),
                ],
                max_length=255,
                verbose_name="Категория покупателя",
            ),
        ),
    ]
