# Generated by Django 5.0.6 on 2024-06-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_alter_purchase_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseevent",
            options={
                "ordering": ["start_at"],
                "verbose_name": "Купленное мероприятие",
                "verbose_name_plural": "Купленное мероприятие",
            },
        ),
    ]
