# Generated by Django 5.0.6 on 2024-06-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_alter_purchaseevent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/purchases/qr_code",
                verbose_name="QR-код",
            ),
        ),
    ]
