# Generated by Django 5.0.6 on 2024-06-12 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_remove_eventprice_event_eventscheduleprice"),
        ("tickets", "0009_purchase_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketevent",
            name="event_schedule",
        ),
        migrations.AlterField(
            model_name="basketevent",
            name="event_price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_events",
                to="events.eventscheduleprice",
                verbose_name="Цена",
            ),
        ),
    ]
