# Generated by Django 5.0.6 on 2024-06-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0011_purchase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="yookassa_url",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
    ]
