# Generated by Django 5.0.6 on 2024-06-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_purchase_yookassa_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="total_price",
            field=models.PositiveIntegerField(default=0, verbose_name="Стоимость"),
            preserve_default=False,
        ),
    ]
