# Generated by Django 5.0.6 on 2024-06-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_purchase_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("CHILD", "Child"),
                    ("STUDENT", "Student"),
                    ("RETIREE", "Retiree"),
                    ("SET", "Set"),
                ],
                max_length=255,
                verbose_name="Категория покупателя",
            ),
        ),
    ]
