# Generated by Django 5.0.6 on 2024-06-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0014_alter_purchaseevent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketevent",
            name="set_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="ID единого билета"),
        ),
        migrations.AlterField(
            model_name="purchaseevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("CHILD", "Child"),
                    ("STUDENT", "Student"),
                    ("RETIREE", "Retiree"),
                ],
                max_length=255,
                verbose_name="Категория покупателя",
            ),
        ),
    ]
