# Generated by Django 5.0.6 on 2024-06-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0015_basketevent_set_id_alter_purchaseevent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseevent",
            name="set_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="ID единого билета"),
        ),
    ]
