# Generated by Django 5.0.6 on 2024-06-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0020_reviewimage_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewimage",
            name="rate",
        ),
        migrations.AddField(
            model_name="review",
            name="rate",
            field=models.PositiveIntegerField(default=5, verbose_name="Рейтинг"),
            preserve_default=False,
        ),
    ]
