# Generated by Django 5.0.6 on 2024-06-15 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0033_remove_eventset_bitrix_id"),
        ("tickets", "0021_remove_reviewimage_rate_review_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="purchase",
        ),
        migrations.AddField(
            model_name="review",
            name="event",
            field=models.ForeignKey(
                default=13,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="events.event",
                verbose_name="Покупка",
            ),
            preserve_default=False,
        ),
    ]
