# Generated by Django 5.0.6 on 2024-06-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0023_review_user_alter_review_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2020-01-01", verbose_name="Дата"),
            preserve_default=False,
        ),
    ]
