# Generated by Django 5.0.6 on 2024-06-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0024_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("SUCCESS", "Success"),
                    ("VISITED", "Visited"),
                    ("CLOSED", "Closed"),
                ],
                default="NEW",
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
